### ISSUE TITLE
Two Admins to Deactivate or Demote

### ISSUE THREAD

**Issue by joshdbarton** [NSS-Day-Cohort-59/meticulous-magpies#2]
As the Tabloid Product Owner, I would like to require that two admins agree to deactivate another admin or to change an admin's user type.

**Comment by DanielOhrin** [comment]
Add functionality to AdminRequest
Add the request, then check if there are two yet. If there are, execute changing their IsCurrent to 0, and then execute the requests.
Display Message for current requests on user

**Comment by DanielOhrin** [comment]
Only use AdminRequest if the user in question is not an Admin

**Comment by DanielOhrin** [comment]
make sure the same admin can't request twice on same user
